# <center>Data Cleaning

### Section 1: Load all the datasets into dataframes

In [1]:
import pandas as pd
customers = pd.read_csv("../data/raw/customers.csv")

In [2]:
customers

,CustomerID,CompanyName,Industry,Country,State,City,EmployeeCount,AnnualRevenue,CompanySize,Website,JoinDate,SalesRepID,CustomerSuccessID,CustomerStatus,HealthScore
0,C000001,United Foster Holdings,Government,France,California,Veronicastad,1257,89241106.0,Large,"fisher,bakerandwalls.com",2023-07-17 05:56:53,E00289,E01307,Active,95
1,C000002,Dynamic Griffin Labs,Education,France,New Hampshire,New Marissa,47,2018500.0,Startup,kelleyllc.com,2018-03-27 07:13:11,E01056,E01190,Churned,60
2,C000003,Blue Patton Industries,Logistics,Canada,Utah,NaN,27,1857461.0,Startup,ali-wheeler.com,2021-02-05 04:33:47,E00608,E00732,Active,83
3,C000004,Quantum Butler Consulting,Technology,Italy,Oklahoma,Taylorbury,126,5313592.0,Small,stephensgroup.com,2025-12-26 00:18:09,E00618,E00924,Active,92
4,C000005,Next Young Systems,Construction,Singapore,Missouri,Anthonyside,179,7496256.0,Small,branch-stevens.com,2020-02-11 23:34:49,E00912,E00720,Active,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C009996,Dynamic Johnson Industries,Telecom,USA,Georgia,Stephaniebury,695,48482598.0,Medium,perezgroup.com,2020-01-04 00:23:46,E00871,E01345,Active,62
9996,C009997,Dynamic Hernandez Systems,Hospitality,UK,Michigan,New Meganfurt,12218,616065087.0,Enterprise,thompson-ingram.com,2023-08-14 13:13:42,E00538,E01057,Active,76
9997,C009998,United Bowen Networks,Government,Australia,Minnesota,North Keithton,17,1172340.0,Startup,"whitaker,sanchezandtorres.com",2018-08-31 16:39:45,E00941,E01245,Active,35
9998,C009999,Blue Montgomery Group,Energy,Saudi Arabia,Maine,Derekside,12,108671.0,Startup,"adkins,shermanandrhodes.com",2024-09-20 15:30:28,E00111,E01314,Inactive,48
9999,C010000,Elite Fuller Consulting,Technology,France,Pennsylvania,Port Dianeton,33,752628.0,Startup,"hood,floresandknight.com",2024-04-19 06:56:27,E01193,E00390,Active,98

In [3]:
employees = pd.read_csv("../data/raw/employees.csv")

In [4]:
employees

,EmployeeID,FirstName,LastName,Department,Salary,HireDate,PerformanceScore,ManagerID
0,E00001,Danielle,Reyes,Sales,151400,2025-08-18 02:10:20,3.35,E00306
1,E00002,Angel,Rose,Product,115818,2024-11-11 09:39:11,2.67,E00634
2,E00003,Joshua,Burch,Customer Success,39703,2020-01-04 15:53:46,3.31,E01152
3,E00004,Jeffrey,Montoya,Support,107099,2024-02-08 16:23:09,3.78,E00625
4,E00005,Jill,Solis,Engineering,191921,2025-07-12 19:33:38,2.93,E00939
...,...,...,...,...,...,...,...,...
1345,E01346,Micheal,Ward,Marketing,210674,2022-09-29 23:46:27,4.79,E00511
1346,E01347,Stacey,Porter,Sales,149598,2024-04-29 11:47:01,2.45,E00540
1347,E01348,Tracey,Bradley,Sales,84334,2024-04-05 00:19:18,2.35,E00016
1348,E01349,Steven,Richardson,Product,103648,2018-12-28 23:57:02,3.16,E00243
1349,E01350,Juan,Scott,Engineering,57054,2025-04-22 23:48:38,4.01,E01231

In [5]:
feature_usage = pd.read_csv("../data/raw/feature_usage.csv")

In [6]:
feature_usage

,FeatureUsageID,SubscriptionID,CustomerID,Feature,TimesUsed,UniqueUsers,AvgDurationMinutes,LastUsed,PlanName
0,F00000001,S000001,C006903,Report Export,2363,47,81.76,2022-05-18 22:06:37,Professional
1,F00000002,S000001,C006903,Workflow Automation,1310,34,36.66,2024-06-27 01:40:30,Professional
2,F00000003,S000001,C006903,REST API,2001,47,65.54,2025-10-22 14:41:22,Professional
3,F00000004,S000002,C006842,REST API,3049,51,18.06,2023-04-21 20:52:12,Starter
4,F00000005,S000002,C006842,Workflow Automation,3989,3,24.31,2024-11-25 07:02:23,Starter
...,...,...,...,...,...,...,...,...,...
67400,F00067401,S002888,C004793,AI Assistant,1983,28,89.29,2020-04-16 17:08:35,Scale
67401,F00067402,S004778,C007862,Team Collaboration,700,48,11.89,2022-09-03 19:27:22,Enterprise
67402,F00067403,S011502,C008800,Integrations,815,54,32.07,2023-08-03 11:33:15,Growth
67403,F00067404,S000420,C001653,Integrations,3576,20,5.41,2023-04-07 15:20:40,Scale
67404,F00067405,S004516,C002045,REST API,2621,15,41.48,2018-06-20 19:22:27,Enterprise

In [7]:
invoices = pd.read_csv("../data/raw/invoices.csv")

In [8]:
invoices

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency
0,I0000001,S000001,C006903,2020-05-21 02:15:43,2020-06-20 02:15:43,3,Professional,129,0.0,Overdue,15,129.0,19.35,148.35,SGD
1,I0000002,S000001,C006903,2020-06-20 02:15:43,2020-07-20 02:15:43,3,Professional,129,0.0,Paid,15,129.0,19.35,148.35,SGD
2,I0000003,S000001,C006903,2020-07-20 02:15:43,2020-08-19 02:15:43,3,Professional,129,0.0,Overdue,15,129.0,19.35,148.35,SGD
3,I0000004,S000001,C006903,2020-08-19 02:15:43,2020-09-18 02:15:43,3,Professional,129,0.0,Paid,10,129.0,12.90,141.90,SGD
4,I0000005,S000001,C006903,2020-09-18 02:15:43,2020-10-18 02:15:43,3,Professional,129,0.0,Pending,10,129.0,12.90,141.90,SGD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487483,I0487484,S014999,C003846,2025-10-01 22:17:49,2025-10-31 22:17:49,1,Starter,29,0.0,Paid,8,29.0,2.32,31.32,SGD
487484,I0487485,S014999,C003846,2025-10-31 22:17:49,2025-11-30 22:17:49,1,Starter,29,0.0,Paid,10,29.0,2.90,31.90,SGD
487485,I0487486,S014999,C003846,2025-11-30 22:17:49,2025-12-30 22:17:49,1,Starter,29,0.0,Pending,18,29.0,5.22,34.22,SGD
487486,I0487487,S014999,C003846,2025-12-30 22:17:49,2026-01-29 22:17:49,1,Starter,29,0.0,Paid,10,29.0,2.90,31.90,SGD
487487,I0487488,S015000,C007481,2020-05-18 11:14:47,2020-06-17 11:14:47,3,Professional,129,0.0,Paid,15,129.0,19.35,148.35,USD

In [9]:
payments = pd.read_csv("../data/raw/payments.csv")

In [10]:
payments

,PaymentID,InvoiceID,CustomerID,PaymentDate,PaymentMethod,Amount,Currency,Status
0,P0000001,I0000002,C006903,2020-07-14 02:15:43,Stripe,148.35,SGD,Completed
1,P0000002,I0000004,C006903,2020-08-29 02:15:43,Debit Card,141.90,SGD,Completed
2,P0000003,I0000007,C006903,2020-11-27 02:15:43,Debit Card,141.90,SGD,Completed
3,P0000004,I0000008,C006903,2021-01-13 02:15:43,Debit Card,135.45,SGD,Completed
4,P0000005,I0000009,C006903,2021-02-07 02:15:43,PayPal,135.45,SGD,Completed
...,...,...,...,...,...,...,...,...
438379,P0438380,I0142207,C003762,2021-09-11 19:24:09,Google Pay,28.35,ZAR,Completed
438380,P0438381,I0022885,C002995,2021-12-06 12:07:59,Credit Card,93.22,SGD,Completed
438381,P0438382,I0346537,C009609,2021-06-20 22:30:39,Bank Transfer,64.90,SAR,Completed
438382,P0438383,I0392443,C000825,2019-06-29 09:55:20,Bank Transfer,34.81,CAD,Completed
438383,P0438384,I0037854,C004131,2020-08-26 15:07:03,Google Pay,113.52,PKR,Completed

In [11]:
plans = pd.read_csv("../data/raw/plans.csv")

In [12]:
plans

,PlanID,PlanName,MonthlyPrice,BillingCycle,APIQuota,StorageLimitGB,AIRequests,SupportTier
0,1,Starter,29,Monthly,10000,25,500,Community
1,2,Basic,59,Monthly,50000,100,2500,Email
2,3,Professional,129,Monthly,100000,250,10000,Priority Email
3,4,Business,249,Monthly,250000,500,30000,Priority
4,5,Enterprise,499,Monthly,500000,1000,100000,Dedicated
5,6,Enterprise Plus,999,Monthly,1000000,5000,500000,Enterprise
6,7,Startup,39,Yearly,25000,50,1000,Email
7,8,Growth,79,Yearly,75000,150,5000,Priority Email
8,9,Scale,179,Yearly,150000,500,20000,Priority
9,10,Corporate,349,Yearly,350000,1500,60000,Dedicated
10,11,Ultimate,1499,Yearly,2500000,10000,1000000,Enterprise
11,12,Legacy,199,Legacy,80000,200,8000,Legacy

In [13]:
refunds = pd.read_csv("../data/raw/refunds.csv")

In [14]:
refunds

,RefundID,PaymentID,InvoiceID,CustomerID,RefundDate,RefundAmount,Reason,Status
0,R0000001,P0146032,I0162697,C003992,2024-06-14 04:51:32,33.35,Customer Request,Processed
1,R0000002,P0208035,I0231624,C008204,2023-07-17 04:50:04,67.78,Subscription Cancellation,Processed
2,R0000003,P0213316,I0237443,C001343,2025-01-02 18:20:14,116.10,Subscription Cancellation,Processed
3,R0000004,P0044791,I0049821,C004912,2020-07-30 19:30:38,200.66,Billing Error,Processed
4,R0000005,P0356568,I0396642,C009073,2023-07-17 12:48:55,25.01,Fraud,Processed
...,...,...,...,...,...,...,...,...
17565,R0017566,P0383869,I0426973,C007610,2024-11-27 13:20:07,33.64,Billing Error,Processed
17566,R0017567,P0127690,I0142138,C001588,2020-10-15 21:26:25,29.75,Billing Error,Processed
17567,R0017568,P0328916,I0365876,C006566,2025-03-07 03:18:29,121.78,Billing Error,Processed
17568,R0017569,P0187090,I0208313,C007538,2022-11-11 15:55:47,140.93,Billing Error,Processed
17569,R0017570,P0146440,I0163134,C008153,2021-11-20 02:44:09,158.10,Billing Error,Processed

In [15]:
subscriptions = pd.read_csv("../data/raw/subscriptions.csv")

In [16]:
subscriptions

,SubscriptionID,CustomerID,PlanID,BillingCycle,Status,DiscountPercent,StartDate,RenewalDate,CancelDate,AutoRenew,PlanName,MonthlyPrice,AnnualContractValue
0,S000001,C006903,3,Monthly,Active,0.0,2020-05-21 02:15:43,2020-06-20 02:15:43,NaN,Yes,Professional,129,1548.0
1,S000002,C006842,1,Monthly,Active,0.0,2020-08-14 04:13:04,2020-09-13 04:13:04,NaN,Yes,Starter,29,348.0
2,S000003,C000666,1,Monthly,Active,0.0,2023-09-18 11:58:46,2023-10-18 11:58:46,NaN,Yes,Starter,29,348.0
3,S000004,C002956,3,Yearly,Active,10.0,2021-04-26 11:57:16,2022-04-26 11:57:16,NaN,Yes,Professional,129,1393.2
4,S000005,C009886,2,Monthly,Active,0.0,2023-12-17 22:35:27,2024-01-16 22:35:27,NaN,Yes,Basic,59,708.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,S014996,C008146,2,Monthly,Active,0.0,2018-09-15 22:25:44,2018-10-15 22:25:44,NaN,Yes,Basic,59,708.0
14996,S014997,C003810,3,Yearly,Active,10.0,2021-09-11 02:53:55,2022-09-11 02:53:55,NaN,Yes,Professional,129,1393.2
14997,S014998,C005729,3,Monthly,Active,0.0,2022-07-30 00:18:23,2022-08-29 00:18:23,NaN,No,Professional,129,1548.0
14998,S014999,C003846,1,Monthly,Active,0.0,2021-07-24 22:17:49,2021-08-23 22:17:49,NaN,Yes,Starter,29,348.0
14999,S015000,C007481,3,Yearly,Cancelled,0.0,2020-05-18 11:14:47,2021-05-18 11:14:47,2021-02-17 11:14:47,Yes,Professional,129,1548.0

In [17]:
support_tickets = pd.read_csv("../data/raw/support_tickets.csv")

In [18]:
support_tickets

,TicketID,CustomerID,AgentID,Category,Priority,Status,CreatedDate,ResolvedDate,ResolutionHours,CustomerSatisfaction
0,T0000001,C000001,E00904,Account,Low,Closed,2025-09-17 04:52:56,2025-09-20 08:52:56,76.0,1
1,T0000002,C000001,E00969,Performance,Medium,Open,2024-02-07 16:20:56,2024-02-09 14:20:56,46.0,2
2,T0000003,C000001,E00171,Billing,High,Resolved,2025-05-24 10:38:49,2025-05-29 16:38:49,126.0,1
3,T0000004,C000002,E01153,Security,Low,Resolved,2019-07-27 13:55:05,2019-07-31 08:55:05,91.0,5
4,T0000005,C000003,E00915,Feature Request,Medium,Resolved,2023-01-02 10:13:28,2023-01-07 14:13:28,124.0,5
...,...,...,...,...,...,...,...,...,...,...
20049,T0020050,C008722,E00684,Technical,Low,Pending,2025-09-22 08:59:26,2025-09-28 09:59:26,145.0,4
20050,T0020051,C004261,E01140,Performance,Medium,Closed,2025-12-19 04:40:00,2025-12-23 00:40:00,92.0,5
20051,T0020052,C006969,E00316,Performance,High,Pending,2022-10-25 20:16:05,2022-10-31 11:16:05,135.0,1
20052,T0020053,C008315,E00799,Technical,Low,Resolved,2024-05-26 22:35:22,2024-05-28 11:35:22,37.0,4
20053,T0020054,C007222,E01260,Bug Report,Medium,Open,2020-02-25 09:43:56,2020-03-05 23:43:56,230.0,5

In [19]:
usage_logs = pd.read_csv("../data/raw/usage_logs.csv")

In [20]:
usage_logs

,UsageID,SubscriptionID,CustomerID,UsageDate,Platform,Device,Region,SessionMinutes,APICalls,AIRequests,StorageGB,Logins,FilesUploaded,ReportsGenerated
0,U00000001,S000001,C006903,2021-07-15 19:42:58,iOS,Windows,Africa,181,246,58,5.04,4,11,2
1,U00000002,S000001,C006903,2025-12-06 19:03:27,Android,Linux,Asia,49,249,36,5.35,4,25,4
2,U00000003,S000001,C006903,2025-05-23 04:26:22,iOS,Linux,Africa,199,245,55,3.92,9,19,4
3,U00000004,S000001,C006903,2023-07-16 23:47:34,Desktop,iPhone,South America,195,281,51,3.52,6,17,2
4,U00000005,S000001,C006903,2022-10-18 21:14:00,Web,Linux,Asia,236,248,42,2.69,5,17,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941774,U01941775,S004058,C002414,2024-09-08 23:42:47,Android,Mac,Africa,41,257,45,2.86,3,18,3
1941775,U01941776,S011708,C008543,2024-11-27 05:25:56,Desktop,Linux,Africa,168,271,47,5.53,12,16,1
1941776,U01941777,S012599,C005909,2025-07-07 15:16:04,Web,iPhone,Asia,63,289,42,5.09,10,14,1
1941777,U01941778,S008289,C008790,2022-12-17 04:28:50,Android,Mac,South America,62,259,47,1.72,4,26,1
1941778,U01941779,S012500,C001911,2024-12-30 09:55:00,Desktop,iPhone,Middle East,147,243,49,1.51,7,15,2

### Section 2: Quick Overview of the datasets

1. customers:

In [21]:
customers.shape

(10000, 15)

In [22]:
customers.dtypes

CustomerID            object
CompanyName           object
Industry              object
Country               object
State                 object
City                  object
EmployeeCount          int64
AnnualRevenue        float64
CompanySize           object
Website               object
JoinDate              object
SalesRepID            object
CustomerSuccessID     object
CustomerStatus        object
HealthScore            int64
dtype: object

In [23]:
customers.columns

Index(['CustomerID', 'CompanyName', 'Industry', 'Country', 'State', 'City',
       'EmployeeCount', 'AnnualRevenue', 'CompanySize', 'Website', 'JoinDate',
       'SalesRepID', 'CustomerSuccessID', 'CustomerStatus', 'HealthScore'],
      dtype='object')

In [24]:
customers.head()

,CustomerID,CompanyName,Industry,Country,State,City,EmployeeCount,AnnualRevenue,CompanySize,Website,JoinDate,SalesRepID,CustomerSuccessID,CustomerStatus,HealthScore
0,C000001,United Foster Holdings,Government,France,California,Veronicastad,1257,89241106.0,Large,"fisher,bakerandwalls.com",2023-07-17 05:56:53,E00289,E01307,Active,95
1,C000002,Dynamic Griffin Labs,Education,France,New Hampshire,New Marissa,47,2018500.0,Startup,kelleyllc.com,2018-03-27 07:13:11,E01056,E01190,Churned,60
2,C000003,Blue Patton Industries,Logistics,Canada,Utah,NaN,27,1857461.0,Startup,ali-wheeler.com,2021-02-05 04:33:47,E00608,E00732,Active,83
3,C000004,Quantum Butler Consulting,Technology,Italy,Oklahoma,Taylorbury,126,5313592.0,Small,stephensgroup.com,2025-12-26 00:18:09,E00618,E00924,Active,92
4,C000005,Next Young Systems,Construction,Singapore,Missouri,Anthonyside,179,7496256.0,Small,branch-stevens.com,2020-02-11 23:34:49,E00912,E00720,Active,86

In [25]:
customers.tail()

,CustomerID,CompanyName,Industry,Country,State,City,EmployeeCount,AnnualRevenue,CompanySize,Website,JoinDate,SalesRepID,CustomerSuccessID,CustomerStatus,HealthScore
9995,C009996,Dynamic Johnson Industries,Telecom,USA,Georgia,Stephaniebury,695,48482598.0,Medium,perezgroup.com,2020-01-04 00:23:46,E00871,E01345,Active,62
9996,C009997,Dynamic Hernandez Systems,Hospitality,UK,Michigan,New Meganfurt,12218,616065087.0,Enterprise,thompson-ingram.com,2023-08-14 13:13:42,E00538,E01057,Active,76
9997,C009998,United Bowen Networks,Government,Australia,Minnesota,North Keithton,17,1172340.0,Startup,"whitaker,sanchezandtorres.com",2018-08-31 16:39:45,E00941,E01245,Active,35
9998,C009999,Blue Montgomery Group,Energy,Saudi Arabia,Maine,Derekside,12,108671.0,Startup,"adkins,shermanandrhodes.com",2024-09-20 15:30:28,E00111,E01314,Inactive,48
9999,C010000,Elite Fuller Consulting,Technology,France,Pennsylvania,Port Dianeton,33,752628.0,Startup,"hood,floresandknight.com",2024-04-19 06:56:27,E01193,E00390,Active,98

In [26]:
customers.sample()

,CustomerID,CompanyName,Industry,Country,State,City,EmployeeCount,AnnualRevenue,CompanySize,Website,JoinDate,SalesRepID,CustomerSuccessID,CustomerStatus,HealthScore
8347,C008348,Nova Parsons Group,Finance,Brazil,Louisiana,Campbellburgh,2413,135210931.0,Large,moore-blackburn.com,2025-08-15 13:54:27,E00976,E01318,Inactive,67

2. employees:

In [27]:
employees.shape

(1350, 8)

In [28]:
employees.dtypes

EmployeeID           object
FirstName            object
LastName             object
Department           object
Salary                int64
HireDate             object
PerformanceScore    float64
ManagerID            object
dtype: object

In [29]:
employees.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'Department', 'Salary',
       'HireDate', 'PerformanceScore', 'ManagerID'],
      dtype='object')

In [30]:
employees.head()

,EmployeeID,FirstName,LastName,Department,Salary,HireDate,PerformanceScore,ManagerID
0,E00001,Danielle,Reyes,Sales,151400,2025-08-18 02:10:20,3.35,E00306
1,E00002,Angel,Rose,Product,115818,2024-11-11 09:39:11,2.67,E00634
2,E00003,Joshua,Burch,Customer Success,39703,2020-01-04 15:53:46,3.31,E01152
3,E00004,Jeffrey,Montoya,Support,107099,2024-02-08 16:23:09,3.78,E00625
4,E00005,Jill,Solis,Engineering,191921,2025-07-12 19:33:38,2.93,E00939

In [31]:
employees.tail()

,EmployeeID,FirstName,LastName,Department,Salary,HireDate,PerformanceScore,ManagerID
1345,E01346,Micheal,Ward,Marketing,210674,2022-09-29 23:46:27,4.79,E00511
1346,E01347,Stacey,Porter,Sales,149598,2024-04-29 11:47:01,2.45,E00540
1347,E01348,Tracey,Bradley,Sales,84334,2024-04-05 00:19:18,2.35,E00016
1348,E01349,Steven,Richardson,Product,103648,2018-12-28 23:57:02,3.16,E00243
1349,E01350,Juan,Scott,Engineering,57054,2025-04-22 23:48:38,4.01,E01231

In [32]:
employees.sample()

,EmployeeID,FirstName,LastName,Department,Salary,HireDate,PerformanceScore,ManagerID
588,E00589,Nicholas,Peck,Engineering,189544,2023-04-20 08:14:27,4.46,E00005

In [33]:
employees.memory_usage("deep")

Index                 132
EmployeeID          10800
FirstName           10800
LastName            10800
Department          10800
Salary              10800
HireDate            10800
PerformanceScore    10800
ManagerID           10800
dtype: int64

3. feature usage

In [34]:
feature_usage.shape

(67405, 9)

In [35]:
feature_usage.columns

Index(['FeatureUsageID', 'SubscriptionID', 'CustomerID', 'Feature',
       'TimesUsed', 'UniqueUsers', 'AvgDurationMinutes', 'LastUsed',
       'PlanName'],
      dtype='object')

In [36]:
feature_usage.dtypes

FeatureUsageID         object
SubscriptionID         object
CustomerID             object
Feature                object
TimesUsed               int64
UniqueUsers             int64
AvgDurationMinutes    float64
LastUsed               object
PlanName               object
dtype: object

In [37]:
 feature_usage.head()

,FeatureUsageID,SubscriptionID,CustomerID,Feature,TimesUsed,UniqueUsers,AvgDurationMinutes,LastUsed,PlanName
0,F00000001,S000001,C006903,Report Export,2363,47,81.76,2022-05-18 22:06:37,Professional
1,F00000002,S000001,C006903,Workflow Automation,1310,34,36.66,2024-06-27 01:40:30,Professional
2,F00000003,S000001,C006903,REST API,2001,47,65.54,2025-10-22 14:41:22,Professional
3,F00000004,S000002,C006842,REST API,3049,51,18.06,2023-04-21 20:52:12,Starter
4,F00000005,S000002,C006842,Workflow Automation,3989,3,24.31,2024-11-25 07:02:23,Starter

In [38]:
feature_usage.tail()

,FeatureUsageID,SubscriptionID,CustomerID,Feature,TimesUsed,UniqueUsers,AvgDurationMinutes,LastUsed,PlanName
67400,F00067401,S002888,C004793,AI Assistant,1983,28,89.29,2020-04-16 17:08:35,Scale
67401,F00067402,S004778,C007862,Team Collaboration,700,48,11.89,2022-09-03 19:27:22,Enterprise
67402,F00067403,S011502,C008800,Integrations,815,54,32.07,2023-08-03 11:33:15,Growth
67403,F00067404,S000420,C001653,Integrations,3576,20,5.41,2023-04-07 15:20:40,Scale
67404,F00067405,S004516,C002045,REST API,2621,15,41.48,2018-06-20 19:22:27,Enterprise

In [39]:
feature_usage.sample()

,FeatureUsageID,SubscriptionID,CustomerID,Feature,TimesUsed,UniqueUsers,AvgDurationMinutes,LastUsed,PlanName
62562,F00062563,S013950,C002184,AI Assistant,1796,2,49.93,2023-11-05 20:51:29,Basic

In [40]:
feature_usage.memory_usage()

Index                    132
FeatureUsageID        539240
SubscriptionID        539240
CustomerID            539240
Feature               539240
TimesUsed             539240
UniqueUsers           539240
AvgDurationMinutes    539240
LastUsed              539240
PlanName              539240
dtype: int64

4. invoices

In [41]:
invoices.shape

(487488, 15)

In [42]:
invoices.columns

Index(['InvoiceID', 'SubscriptionID', 'CustomerID', 'InvoiceDate', 'DueDate',
       'PlanID', 'PlanName', 'MonthlyPrice', 'DiscountPercent', 'Status',
       'TaxRate', 'Subtotal', 'TaxAmount', 'TotalAmount', 'Currency'],
      dtype='object')

In [43]:
invoices.dtypes

InvoiceID           object
SubscriptionID      object
CustomerID          object
InvoiceDate         object
DueDate             object
PlanID               int64
PlanName            object
MonthlyPrice         int64
DiscountPercent    float64
Status              object
TaxRate              int64
Subtotal           float64
TaxAmount          float64
TotalAmount        float64
Currency            object
dtype: object

In [44]:
invoices.head()

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency
0,I0000001,S000001,C006903,2020-05-21 02:15:43,2020-06-20 02:15:43,3,Professional,129,0.0,Overdue,15,129.0,19.35,148.35,SGD
1,I0000002,S000001,C006903,2020-06-20 02:15:43,2020-07-20 02:15:43,3,Professional,129,0.0,Paid,15,129.0,19.35,148.35,SGD
2,I0000003,S000001,C006903,2020-07-20 02:15:43,2020-08-19 02:15:43,3,Professional,129,0.0,Overdue,15,129.0,19.35,148.35,SGD
3,I0000004,S000001,C006903,2020-08-19 02:15:43,2020-09-18 02:15:43,3,Professional,129,0.0,Paid,10,129.0,12.90,141.90,SGD
4,I0000005,S000001,C006903,2020-09-18 02:15:43,2020-10-18 02:15:43,3,Professional,129,0.0,Pending,10,129.0,12.90,141.90,SGD

In [45]:
invoices.tail()

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency
487483,I0487484,S014999,C003846,2025-10-01 22:17:49,2025-10-31 22:17:49,1,Starter,29,0.0,Paid,8,29.0,2.32,31.32,SGD
487484,I0487485,S014999,C003846,2025-10-31 22:17:49,2025-11-30 22:17:49,1,Starter,29,0.0,Paid,10,29.0,2.90,31.90,SGD
487485,I0487486,S014999,C003846,2025-11-30 22:17:49,2025-12-30 22:17:49,1,Starter,29,0.0,Pending,18,29.0,5.22,34.22,SGD
487486,I0487487,S014999,C003846,2025-12-30 22:17:49,2026-01-29 22:17:49,1,Starter,29,0.0,Paid,10,29.0,2.90,31.90,SGD
487487,I0487488,S015000,C007481,2020-05-18 11:14:47,2020-06-17 11:14:47,3,Professional,129,0.0,Paid,15,129.0,19.35,148.35,USD

In [46]:
invoices.sample()

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency
476911,I0476912,S014649,C005464,2024-11-09 23:25:10,2024-12-09 23:25:10,6,Enterprise Plus,999,10.0,Paid,8,899.1,71.93,971.03,EUR

In [47]:
invoices.memory_usage()

Index                  132
InvoiceID          3899904
SubscriptionID     3899904
CustomerID         3899904
InvoiceDate        3899904
DueDate            3899904
PlanID             3899904
PlanName           3899904
MonthlyPrice       3899904
DiscountPercent    3899904
Status             3899904
TaxRate            3899904
Subtotal           3899904
TaxAmount          3899904
TotalAmount        3899904
Currency           3899904
dtype: int64

5. payments

In [48]:
payments.shape

(438384, 8)

In [49]:
payments.dtypes

PaymentID         object
InvoiceID         object
CustomerID        object
PaymentDate       object
PaymentMethod     object
Amount           float64
Currency          object
Status            object
dtype: object

In [50]:
payments.head()

,PaymentID,InvoiceID,CustomerID,PaymentDate,PaymentMethod,Amount,Currency,Status
0,P0000001,I0000002,C006903,2020-07-14 02:15:43,Stripe,148.35,SGD,Completed
1,P0000002,I0000004,C006903,2020-08-29 02:15:43,Debit Card,141.90,SGD,Completed
2,P0000003,I0000007,C006903,2020-11-27 02:15:43,Debit Card,141.90,SGD,Completed
3,P0000004,I0000008,C006903,2021-01-13 02:15:43,Debit Card,135.45,SGD,Completed
4,P0000005,I0000009,C006903,2021-02-07 02:15:43,PayPal,135.45,SGD,Completed

In [51]:
payments.tail()

,PaymentID,InvoiceID,CustomerID,PaymentDate,PaymentMethod,Amount,Currency,Status
438379,P0438380,I0142207,C003762,2021-09-11 19:24:09,Google Pay,28.35,ZAR,Completed
438380,P0438381,I0022885,C002995,2021-12-06 12:07:59,Credit Card,93.22,SGD,Completed
438381,P0438382,I0346537,C009609,2021-06-20 22:30:39,Bank Transfer,64.90,SAR,Completed
438382,P0438383,I0392443,C000825,2019-06-29 09:55:20,Bank Transfer,34.81,CAD,Completed
438383,P0438384,I0037854,C004131,2020-08-26 15:07:03,Google Pay,113.52,PKR,Completed

In [52]:
payments.sample()

,PaymentID,InvoiceID,CustomerID,PaymentDate,PaymentMethod,Amount,Currency,Status
404454,P0404455,I0449932,C003401,2022-08-30 20:38:03,Debit Card,86.9,EUR,Completed

In [53]:
payments.memory_usage()

Index                132
PaymentID        3507072
InvoiceID        3507072
CustomerID       3507072
PaymentDate      3507072
PaymentMethod    3507072
Amount           3507072
Currency         3507072
Status           3507072
dtype: int64

6. plans

In [54]:
plans.shape

(12, 8)

In [55]:
plans.dtypes

PlanID             int64
PlanName          object
MonthlyPrice       int64
BillingCycle      object
APIQuota           int64
StorageLimitGB     int64
AIRequests         int64
SupportTier       object
dtype: object

In [56]:
plans

,PlanID,PlanName,MonthlyPrice,BillingCycle,APIQuota,StorageLimitGB,AIRequests,SupportTier
0,1,Starter,29,Monthly,10000,25,500,Community
1,2,Basic,59,Monthly,50000,100,2500,Email
2,3,Professional,129,Monthly,100000,250,10000,Priority Email
3,4,Business,249,Monthly,250000,500,30000,Priority
4,5,Enterprise,499,Monthly,500000,1000,100000,Dedicated
5,6,Enterprise Plus,999,Monthly,1000000,5000,500000,Enterprise
6,7,Startup,39,Yearly,25000,50,1000,Email
7,8,Growth,79,Yearly,75000,150,5000,Priority Email
8,9,Scale,179,Yearly,150000,500,20000,Priority
9,10,Corporate,349,Yearly,350000,1500,60000,Dedicated
10,11,Ultimate,1499,Yearly,2500000,10000,1000000,Enterprise
11,12,Legacy,199,Legacy,80000,200,8000,Legacy

In [57]:
plans.memory_usage()

Index             132
PlanID             96
PlanName           96
MonthlyPrice       96
BillingCycle       96
APIQuota           96
StorageLimitGB     96
AIRequests         96
SupportTier        96
dtype: int64

7. refunds

In [58]:
refunds.shape

(17570, 8)

In [59]:
refunds.dtypes

RefundID         object
PaymentID        object
InvoiceID        object
CustomerID       object
RefundDate       object
RefundAmount    float64
Reason           object
Status           object
dtype: object

In [60]:
refunds.head()

,RefundID,PaymentID,InvoiceID,CustomerID,RefundDate,RefundAmount,Reason,Status
0,R0000001,P0146032,I0162697,C003992,2024-06-14 04:51:32,33.35,Customer Request,Processed
1,R0000002,P0208035,I0231624,C008204,2023-07-17 04:50:04,67.78,Subscription Cancellation,Processed
2,R0000003,P0213316,I0237443,C001343,2025-01-02 18:20:14,116.10,Subscription Cancellation,Processed
3,R0000004,P0044791,I0049821,C004912,2020-07-30 19:30:38,200.66,Billing Error,Processed
4,R0000005,P0356568,I0396642,C009073,2023-07-17 12:48:55,25.01,Fraud,Processed

In [61]:
refunds.tail()

,RefundID,PaymentID,InvoiceID,CustomerID,RefundDate,RefundAmount,Reason,Status
17565,R0017566,P0383869,I0426973,C007610,2024-11-27 13:20:07,33.64,Billing Error,Processed
17566,R0017567,P0127690,I0142138,C001588,2020-10-15 21:26:25,29.75,Billing Error,Processed
17567,R0017568,P0328916,I0365876,C006566,2025-03-07 03:18:29,121.78,Billing Error,Processed
17568,R0017569,P0187090,I0208313,C007538,2022-11-11 15:55:47,140.93,Billing Error,Processed
17569,R0017570,P0146440,I0163134,C008153,2021-11-20 02:44:09,158.10,Billing Error,Processed

In [62]:
refunds.sample()

,RefundID,PaymentID,InvoiceID,CustomerID,RefundDate,RefundAmount,Reason,Status
7662,R0007663,P0014410,I0016045,C000230,2022-06-28 03:02:18,86.9,Billing Error,Processed

8. subscriptions

In [63]:
subscriptions.shape

(15000, 13)

In [64]:
subscriptions.dtypes

SubscriptionID          object
CustomerID              object
PlanID                   int64
BillingCycle            object
Status                  object
DiscountPercent        float64
StartDate               object
RenewalDate             object
CancelDate              object
AutoRenew               object
PlanName                object
MonthlyPrice             int64
AnnualContractValue    float64
dtype: object

In [65]:
subscriptions.head()

,SubscriptionID,CustomerID,PlanID,BillingCycle,Status,DiscountPercent,StartDate,RenewalDate,CancelDate,AutoRenew,PlanName,MonthlyPrice,AnnualContractValue
0,S000001,C006903,3,Monthly,Active,0.0,2020-05-21 02:15:43,2020-06-20 02:15:43,NaN,Yes,Professional,129,1548.0
1,S000002,C006842,1,Monthly,Active,0.0,2020-08-14 04:13:04,2020-09-13 04:13:04,NaN,Yes,Starter,29,348.0
2,S000003,C000666,1,Monthly,Active,0.0,2023-09-18 11:58:46,2023-10-18 11:58:46,NaN,Yes,Starter,29,348.0
3,S000004,C002956,3,Yearly,Active,10.0,2021-04-26 11:57:16,2022-04-26 11:57:16,NaN,Yes,Professional,129,1393.2
4,S000005,C009886,2,Monthly,Active,0.0,2023-12-17 22:35:27,2024-01-16 22:35:27,NaN,Yes,Basic,59,708.0

In [66]:
subscriptions.tail()

,SubscriptionID,CustomerID,PlanID,BillingCycle,Status,DiscountPercent,StartDate,RenewalDate,CancelDate,AutoRenew,PlanName,MonthlyPrice,AnnualContractValue
14995,S014996,C008146,2,Monthly,Active,0.0,2018-09-15 22:25:44,2018-10-15 22:25:44,NaN,Yes,Basic,59,708.0
14996,S014997,C003810,3,Yearly,Active,10.0,2021-09-11 02:53:55,2022-09-11 02:53:55,NaN,Yes,Professional,129,1393.2
14997,S014998,C005729,3,Monthly,Active,0.0,2022-07-30 00:18:23,2022-08-29 00:18:23,NaN,No,Professional,129,1548.0
14998,S014999,C003846,1,Monthly,Active,0.0,2021-07-24 22:17:49,2021-08-23 22:17:49,NaN,Yes,Starter,29,348.0
14999,S015000,C007481,3,Yearly,Cancelled,0.0,2020-05-18 11:14:47,2021-05-18 11:14:47,2021-02-17 11:14:47,Yes,Professional,129,1548.0

In [67]:
subscriptions.sample()

,SubscriptionID,CustomerID,PlanID,BillingCycle,Status,DiscountPercent,StartDate,RenewalDate,CancelDate,AutoRenew,PlanName,MonthlyPrice,AnnualContractValue
12496,S012497,C007454,7,Monthly,Active,0.0,2023-08-15 00:29:28,2023-09-14 00:29:28,NaN,No,Startup,39,468.0

9. support_tickets

In [68]:
support_tickets.shape

(20054, 10)

In [69]:
support_tickets.dtypes

TicketID                 object
CustomerID               object
AgentID                  object
Category                 object
Priority                 object
Status                   object
CreatedDate              object
ResolvedDate             object
ResolutionHours         float64
CustomerSatisfaction      int64
dtype: object

In [70]:
support_tickets.head()

,TicketID,CustomerID,AgentID,Category,Priority,Status,CreatedDate,ResolvedDate,ResolutionHours,CustomerSatisfaction
0,T0000001,C000001,E00904,Account,Low,Closed,2025-09-17 04:52:56,2025-09-20 08:52:56,76.0,1
1,T0000002,C000001,E00969,Performance,Medium,Open,2024-02-07 16:20:56,2024-02-09 14:20:56,46.0,2
2,T0000003,C000001,E00171,Billing,High,Resolved,2025-05-24 10:38:49,2025-05-29 16:38:49,126.0,1
3,T0000004,C000002,E01153,Security,Low,Resolved,2019-07-27 13:55:05,2019-07-31 08:55:05,91.0,5
4,T0000005,C000003,E00915,Feature Request,Medium,Resolved,2023-01-02 10:13:28,2023-01-07 14:13:28,124.0,5

In [71]:
support_tickets.tail()

,TicketID,CustomerID,AgentID,Category,Priority,Status,CreatedDate,ResolvedDate,ResolutionHours,CustomerSatisfaction
20049,T0020050,C008722,E00684,Technical,Low,Pending,2025-09-22 08:59:26,2025-09-28 09:59:26,145.0,4
20050,T0020051,C004261,E01140,Performance,Medium,Closed,2025-12-19 04:40:00,2025-12-23 00:40:00,92.0,5
20051,T0020052,C006969,E00316,Performance,High,Pending,2022-10-25 20:16:05,2022-10-31 11:16:05,135.0,1
20052,T0020053,C008315,E00799,Technical,Low,Resolved,2024-05-26 22:35:22,2024-05-28 11:35:22,37.0,4
20053,T0020054,C007222,E01260,Bug Report,Medium,Open,2020-02-25 09:43:56,2020-03-05 23:43:56,230.0,5

In [72]:
support_tickets.sample()

,TicketID,CustomerID,AgentID,Category,Priority,Status,CreatedDate,ResolvedDate,ResolutionHours,CustomerSatisfaction
3765,T0003766,C001902,E00610,Feature Request,Medium,Resolved,2023-12-04 07:36:35,2023-12-12 04:36:35,189.0,2

10. usage_logs

In [73]:
usage_logs.shape

(1941779, 14)

In [74]:
usage_logs.dtypes

UsageID              object
SubscriptionID       object
CustomerID           object
UsageDate            object
Platform             object
Device               object
Region               object
SessionMinutes        int64
APICalls              int64
AIRequests            int64
StorageGB           float64
Logins                int64
FilesUploaded         int64
ReportsGenerated      int64
dtype: object

In [75]:
usage_logs.head()

,UsageID,SubscriptionID,CustomerID,UsageDate,Platform,Device,Region,SessionMinutes,APICalls,AIRequests,StorageGB,Logins,FilesUploaded,ReportsGenerated
0,U00000001,S000001,C006903,2021-07-15 19:42:58,iOS,Windows,Africa,181,246,58,5.04,4,11,2
1,U00000002,S000001,C006903,2025-12-06 19:03:27,Android,Linux,Asia,49,249,36,5.35,4,25,4
2,U00000003,S000001,C006903,2025-05-23 04:26:22,iOS,Linux,Africa,199,245,55,3.92,9,19,4
3,U00000004,S000001,C006903,2023-07-16 23:47:34,Desktop,iPhone,South America,195,281,51,3.52,6,17,2
4,U00000005,S000001,C006903,2022-10-18 21:14:00,Web,Linux,Asia,236,248,42,2.69,5,17,3

In [76]:
usage_logs.tail()

,UsageID,SubscriptionID,CustomerID,UsageDate,Platform,Device,Region,SessionMinutes,APICalls,AIRequests,StorageGB,Logins,FilesUploaded,ReportsGenerated
1941774,U01941775,S004058,C002414,2024-09-08 23:42:47,Android,Mac,Africa,41,257,45,2.86,3,18,3
1941775,U01941776,S011708,C008543,2024-11-27 05:25:56,Desktop,Linux,Africa,168,271,47,5.53,12,16,1
1941776,U01941777,S012599,C005909,2025-07-07 15:16:04,Web,iPhone,Asia,63,289,42,5.09,10,14,1
1941777,U01941778,S008289,C008790,2022-12-17 04:28:50,Android,Mac,South America,62,259,47,1.72,4,26,1
1941778,U01941779,S012500,C001911,2024-12-30 09:55:00,Desktop,iPhone,Middle East,147,243,49,1.51,7,15,2

In [77]:
usage_logs.sample()

,UsageID,SubscriptionID,CustomerID,UsageDate,Platform,Device,Region,SessionMinutes,APICalls,AIRequests,StorageGB,Logins,FilesUploaded,ReportsGenerated
1243712,U01243713,S009623,C005125,2025-06-14 15:55:42,Android,Windows,South America,142,244,32,1.86,5,21,0

### Section 3: Missing Values

1. Customers

In [78]:
customers.isna().sum()

CustomerID             0
CompanyName            0
Industry               0
Country                0
State                  0
City                 150
EmployeeCount          0
AnnualRevenue        120
CompanySize            0
Website               60
JoinDate               0
SalesRepID             0
CustomerSuccessID      0
CustomerStatus         0
HealthScore            0
dtype: int64

In [79]:
(customers.isna().sum()/len(customers))*100

CustomerID           0.0
CompanyName          0.0
Industry             0.0
Country              0.0
State                0.0
City                 1.5
EmployeeCount        0.0
AnnualRevenue        1.2
CompanySize          0.0
Website              0.6
JoinDate             0.0
SalesRepID           0.0
CustomerSuccessID    0.0
CustomerStatus       0.0
HealthScore          0.0
dtype: float64

In [80]:
customers["City"] = customers["City"].fillna("Unknown")

In [81]:
customers["AnnualRevenue"] = customers["AnnualRevenue"].fillna(customers["AnnualRevenue"].median())

In [82]:
customers["Website"] = customers["Website"].fillna("Missing")

In [83]:
customers.isna().sum()

CustomerID           0
CompanyName          0
Industry             0
Country              0
State                0
City                 0
EmployeeCount        0
AnnualRevenue        0
CompanySize          0
Website              0
JoinDate             0
SalesRepID           0
CustomerSuccessID    0
CustomerStatus       0
HealthScore          0
dtype: int64

2. employees

In [84]:
employees.isna().sum()

EmployeeID          0
FirstName           0
LastName            0
Department          0
Salary              0
HireDate            0
PerformanceScore    0
ManagerID           0
dtype: int64

In [85]:
(employees.isna().sum() / len(employees) )*100

EmployeeID          0.0
FirstName           0.0
LastName            0.0
Department          0.0
Salary              0.0
HireDate            0.0
PerformanceScore    0.0
ManagerID           0.0
dtype: float64

3. feature usage

In [86]:
feature_usage.isna().sum()

FeatureUsageID         0
SubscriptionID         0
CustomerID             0
Feature               50
TimesUsed              0
UniqueUsers            0
AvgDurationMinutes     0
LastUsed               0
PlanName               0
dtype: int64

In [87]:
(feature_usage.isna().sum() / len(feature_usage) ) * 100

FeatureUsageID        0.000000
SubscriptionID        0.000000
CustomerID            0.000000
Feature               0.074178
TimesUsed             0.000000
UniqueUsers           0.000000
AvgDurationMinutes    0.000000
LastUsed              0.000000
PlanName              0.000000
dtype: float64

In [88]:
feature_usage[feature_usage["Feature"].isna()]

,FeatureUsageID,SubscriptionID,CustomerID,Feature,TimesUsed,UniqueUsers,AvgDurationMinutes,LastUsed,PlanName
460,F00000461,S000107,C002127,NaN,1297,45,36.35,2023-11-01 00:25:51,Basic
625,F00000626,S000142,C000284,NaN,3588,19,52.05,2018-04-24 06:03:07,Business
1548,F00001549,S000335,C001993,NaN,2488,4,19.63,2025-08-26 05:49:37,Enterprise
3283,F00003284,S000731,C003305,NaN,1664,14,38.43,2023-04-10 09:49:39,Growth
3718,F00003719,S000834,C006223,NaN,1110,5,57.83,2021-11-15 23:40:14,Corporate
4128,F00004129,S000925,C007132,NaN,1814,23,31.69,2021-06-23 14:44:18,Professional
6387,F00006388,S001415,C009452,NaN,3476,17,55.21,2018-09-05 21:19:18,Growth
6478,F00006479,S001432,C007135,NaN,3769,52,29.56,2021-11-05 02:36:15,Starter
9972,F00009973,S002229,C001081,NaN,580,19,12.09,2019-08-31 01:16:36,Enterprise
12953,F00012954,S002905,C006573,NaN,3914,50,78.53,2021-03-25 16:42:56,Professional
14997,F00014998,S003371,C006022,NaN,2060,18,81.20,2020-04-24 08:34:29,Starter
16797,F00016798,S003778,C007428,NaN,3868,15,37.88,2021-09-02 12:39:01,Startup
16931,F00016932,S003810,C007867,NaN,3705,41,85.49,2025-02-16 08:39:58,Basic
17028,F00017029,S003832,C006962,NaN,584,16,28.97,2024-03-31 08:53:07,Basic
18794,F00018795,S004209,C004882,NaN,700,16,83.74,2025-09-06 11:10:16,Business
19410,F00019411,S004345,C008807,NaN,1451,58,13.58,2023-07-07 20:47:45,Professional
19726,F00019727,S004414,C009425,NaN,2485,50,18.94,2024-07-02 12:05:11,Basic
21795,F00021796,S004869,C006043,NaN,1092,58,54.46,2022-11-03 20:44:19,Basic
23168,F00023169,S005178,C009239,NaN,2805,28,18.12,2021-02-09 15:45:07,Starter
29384,F00029385,S006566,C008073,NaN,1470,33,80.70,2020-04-19 05:10:56,Corporate
32246,F00032247,S007205,C001980,NaN,1724,33,5.77,2020-03-22 18:52:32,Basic
32391,F00032392,S007239,C000795,NaN,284,10,34.24,2024-02-28 08:44:17,Enterprise
32534,F00032535,S007273,C001161,NaN,663,52,72.69,2025-01-13 09:18:45,Growth
34274,F00034275,S007664,C003084,NaN,314,10,88.05,2025-12-28 20:03:48,Enterprise Plus
35208,F00035209,S007868,C000592,NaN,1840,52,3.33,2024-02-19 08:46:36,Basic
36415,F00036416,S008130,C002962,NaN,846,10,86.47,2021-11-07 16:54:27,Starter
37558,F00037559,S008378,C006297,NaN,2405,38,69.69,2022-02-08 16:53:47,Enterprise
38565,F00038566,S008602,C005527,NaN,1852,18,18.02,2023-08-30 10:25:27,Basic
40553,F00040554,S009033,C000328,NaN,445,3,67.94,2020-10-04 05:33:18,Scale
41042,F00041043,S009151,C007463,NaN,3000,49,57.77,2019-05-06 09:50:44,Starter
42006,F00042007,S009366,C007955,NaN,1775,8,80.07,2022-08-29 14:14:33,Starter
42175,F00042176,S009405,C007628,NaN,2269,19,32.35,2024-11-18 09:08:15,Basic
43166,F00043167,S009621,C006811,NaN,2233,48,48.46,2020-10-30 10:48:21,Basic
43567,F00043568,S009708,C008141,NaN,1250,23,2.19,2020-04-03 21:20:24,Professional
45385,F00045386,S010100,C008029,NaN,581,21,55.26,2019-09-05 20:28:33,Professional
46735,F00046736,S010407,C006860,NaN,253,34,4.22,2025-02-09 05:26:55,Basic
46779,F00046780,S010417,C000290,NaN,765,37,88.90,2021-04-24 02:40:02,Enterprise Plus
50272,F00050273,S011217,C008458,NaN,3639,19,19.66,2025-02-07 04:58:06,Basic
50794,F00050795,S011327,C004044,NaN,209,48,36.25,2022-01-20 00:03:10,Enterprise
52545,F00052546,S011714,C002293,NaN,353,6,2.80,2023-07-17 04:27:01,Basic
52916,F00052917,S011800,C003296,NaN,2088,57,31.33,2019-05-24 09:38:20,Basic
52936,F00052937,S011807,C002292,NaN,3386,38,36.50,2022-10-07 15:50:28,Basic
53357,F00053358,S011900,C007886,NaN,673,3,71.23,2024-10-06 02:11:42,Legacy
55127,F00055128,S012298,C002434,NaN,1073,25,19.48,2024-12-17 23:16:53,Starter
59345,F00059346,S013239,C004950,NaN,859,31,9.38,2023-04-10 12:34:13,Basic
60277,F00060278,S013454,C006355,NaN,1030,32,71.49,2020-08-17 06:10:54,Startup
61926,F00061927,S013808,C001399,NaN,1016,43,45.61,2022-10-02 04:30:11,Business
63085,F00063086,S014066,C002335,NaN,1984,10,20.83,2020-04-24 09:41:22,Enterprise
63858,F00063859,S014237,C004984,NaN,52,19,30.02,2025-06-04 07:32:39,Starter
65344,F00065345,S014570,C003007,NaN,3262,6,73.42,2020-06-21 13:57:56,Starter

In [89]:
feature_usage["Feature"] = feature_usage["Feature"].fillna("Unknown")

In [90]:
feature_usage.isna().sum()

FeatureUsageID        0
SubscriptionID        0
CustomerID            0
Feature               0
TimesUsed             0
UniqueUsers           0
AvgDurationMinutes    0
LastUsed              0
PlanName              0
dtype: int64

4. invoices

In [91]:
invoices.isna().sum()

InvoiceID             0
SubscriptionID        0
CustomerID            0
InvoiceDate           0
DueDate               0
PlanID                0
PlanName              0
MonthlyPrice          0
DiscountPercent    2507
Status                0
TaxRate               0
Subtotal              0
TaxAmount             0
TotalAmount           0
Currency              0
dtype: int64

In [92]:
(invoices.isna().sum() / len(invoices) )*100

InvoiceID          0.000000
SubscriptionID     0.000000
CustomerID         0.000000
InvoiceDate        0.000000
DueDate            0.000000
PlanID             0.000000
PlanName           0.000000
MonthlyPrice       0.000000
DiscountPercent    0.514269
Status             0.000000
TaxRate            0.000000
Subtotal           0.000000
TaxAmount          0.000000
TotalAmount        0.000000
Currency           0.000000
dtype: float64

In [93]:
invoices["DiscountPercent"] = invoices["DiscountPercent"].fillna(100 - ((invoices["Subtotal"] / invoices["MonthlyPrice"])*100))

In [94]:
invoices.isna().sum()

InvoiceID          0
SubscriptionID     0
CustomerID         0
InvoiceDate        0
DueDate            0
PlanID             0
PlanName           0
MonthlyPrice       0
DiscountPercent    0
Status             0
TaxRate            0
Subtotal           0
TaxAmount          0
TotalAmount        0
Currency           0
dtype: int64

5. payments

In [95]:
payments.isna().sum()

PaymentID        0
InvoiceID        0
CustomerID       0
PaymentDate      0
PaymentMethod    0
Amount           0
Currency         0
Status           0
dtype: int64

6. plans

In [96]:
plans.isna().sum()

PlanID            0
PlanName          0
MonthlyPrice      0
BillingCycle      0
APIQuota          0
StorageLimitGB    0
AIRequests        0
SupportTier       0
dtype: int64

7. refunds

In [97]:
refunds.isna().sum()

RefundID         0
PaymentID        0
InvoiceID        0
CustomerID       0
RefundDate       0
RefundAmount     0
Reason          30
Status           0
dtype: int64

In [98]:
(refunds.isna().sum() / len(refunds))*100

RefundID        0.000000
PaymentID       0.000000
InvoiceID       0.000000
CustomerID      0.000000
RefundDate      0.000000
RefundAmount    0.000000
Reason          0.170746
Status          0.000000
dtype: float64

In [99]:
refunds["Reason"] = refunds["Reason"].fillna("Not Specified")

In [100]:
refunds.isna().sum()

RefundID        0
PaymentID       0
InvoiceID       0
CustomerID      0
RefundDate      0
RefundAmount    0
Reason          0
Status          0
dtype: int64

8. subscriptions

In [101]:
subscriptions.isna().sum()

SubscriptionID             0
CustomerID                 0
PlanID                     0
BillingCycle               0
Status                     0
DiscountPercent           80
StartDate                  0
RenewalDate                0
CancelDate             13048
AutoRenew                  0
PlanName                   0
MonthlyPrice               0
AnnualContractValue        0
dtype: int64

In [102]:
(subscriptions.isna().sum() / len(subscriptions))*100

SubscriptionID          0.000000
CustomerID              0.000000
PlanID                  0.000000
BillingCycle            0.000000
Status                  0.000000
DiscountPercent         0.533333
StartDate               0.000000
RenewalDate             0.000000
CancelDate             86.986667
AutoRenew               0.000000
PlanName                0.000000
MonthlyPrice            0.000000
AnnualContractValue     0.000000
dtype: float64

In [103]:
subscriptions["CancelDate"] = subscriptions["CancelDate"].fillna("Not Cancelled Yet")

In [104]:
subscriptions.loc[
    (subscriptions["Status"] == "Cancelled") & (subscriptions["CancelDate"] == "Not Cancelled Yet"),
    "SubscriptionID"
]

Series([], Name: SubscriptionID, dtype: object)

In [105]:
subscriptions.isna().sum()

SubscriptionID          0
CustomerID              0
PlanID                  0
BillingCycle            0
Status                  0
DiscountPercent        80
StartDate               0
RenewalDate             0
CancelDate              0
AutoRenew               0
PlanName                0
MonthlyPrice            0
AnnualContractValue     0
dtype: int64

In [106]:
subscriptions.groupby("DiscountPercent")["SubscriptionID"].nunique()

DiscountPercent
0.0      7095
5.0      1996
10.0     2423
15.0     1544
20.0     1092
25.0      455
30.0      303
120.0      12
Name: SubscriptionID, dtype: int64

In [107]:
subscriptions.loc[subscriptions["DiscountPercent"] > 100, "DiscountPercent" ] = pd.NA

In [108]:
subscriptions.isna().sum()

SubscriptionID          0
CustomerID              0
PlanID                  0
BillingCycle            0
Status                  0
DiscountPercent        92
StartDate               0
RenewalDate             0
CancelDate              0
AutoRenew               0
PlanName                0
MonthlyPrice            0
AnnualContractValue     0
dtype: int64

In [109]:
subscriptions["DiscountPercent"] = subscriptions["DiscountPercent"].fillna( ( 1 - (subscriptions["AnnualContractValue"] / (subscriptions["MonthlyPrice"]*12) ) ) * 100 )

In [110]:
subscriptions.isna().sum()

SubscriptionID         0
CustomerID             0
PlanID                 0
BillingCycle           0
Status                 0
DiscountPercent        0
StartDate              0
RenewalDate            0
CancelDate             0
AutoRenew              0
PlanName               0
MonthlyPrice           0
AnnualContractValue    0
dtype: int64

In [111]:
subscriptions.isna().sum()

SubscriptionID         0
CustomerID             0
PlanID                 0
BillingCycle           0
Status                 0
DiscountPercent        0
StartDate              0
RenewalDate            0
CancelDate             0
AutoRenew              0
PlanName               0
MonthlyPrice           0
AnnualContractValue    0
dtype: int64

9. support_tickets

In [112]:
support_tickets.isna().sum()

TicketID                 0
CustomerID               0
AgentID                  0
Category                51
Priority                 0
Status                   0
CreatedDate              0
ResolvedDate            40
ResolutionHours          0
CustomerSatisfaction     0
dtype: int64

In [113]:
(support_tickets.isna().sum()/len(support_tickets))*100

TicketID                0.000000
CustomerID              0.000000
AgentID                 0.000000
Category                0.254313
Priority                0.000000
Status                  0.000000
CreatedDate             0.000000
ResolvedDate            0.199461
ResolutionHours         0.000000
CustomerSatisfaction    0.000000
dtype: float64

In [114]:
support_tickets["Category"] = support_tickets["Category"].fillna("Not specified")

In [115]:
support_tickets.isna().sum()

TicketID                 0
CustomerID               0
AgentID                  0
Category                 0
Priority                 0
Status                   0
CreatedDate              0
ResolvedDate            40
ResolutionHours          0
CustomerSatisfaction     0
dtype: int64

In [116]:
support_tickets[support_tickets["ResolvedDate"].isna()]

,TicketID,CustomerID,AgentID,Category,Priority,Status,CreatedDate,ResolvedDate,ResolutionHours,CustomerSatisfaction
405,T0000406,C000201,E00362,Security,Low,Closed,2024-05-14 19:58:58,NaN,198.0,4
616,T0000617,C000312,E00374,Performance,Medium,Closed,2024-12-16 10:21:42,NaN,20.0,3
1573,T0001574,C000802,E00170,Billing,High,Closed,2022-06-04 09:27:25,NaN,214.0,2
1651,T0001652,C000842,E00566,Technical,Low,Closed,2024-11-18 05:11:33,NaN,188.0,1
2112,T0002113,C001063,E01294,Performance,Medium,Closed,2025-12-19 13:10:28,NaN,62.0,2
2155,T0002156,C001086,E00687,Technical,Medium,Closed,2019-07-14 17:58:14,NaN,239.0,3
2181,T0002182,C001096,E00478,Account,Critical,Closed,2020-04-16 23:30:03,NaN,99.0,3
2313,T0002314,C001161,E00219,Technical,Low,Closed,2023-08-25 19:12:33,NaN,238.0,1
2488,T0002489,C001250,E00046,Feature Request,Low,Closed,2024-01-03 07:28:02,NaN,135.0,4
3460,T0003461,C001743,E00258,Technical,High,Closed,2020-05-04 15:43:57,NaN,210.0,5
4133,T0004134,C002095,E00288,Account,Medium,Closed,2025-12-29 06:35:42,NaN,27.0,1
4274,T0004275,C002167,E01207,Billing,High,Closed,2024-10-10 05:21:59,NaN,171.0,4
5291,T0005292,C002687,E00201,Performance,Medium,Closed,2025-11-16 15:50:57,NaN,156.0,4
5456,T0005457,C002770,E01269,Billing,Medium,Closed,2024-12-11 05:18:52,NaN,97.0,5
6334,T0006335,C003212,E00261,Feature Request,Critical,Closed,2025-12-13 15:46:23,NaN,222.0,1
7090,T0007091,C003583,E00360,Performance,Medium,Closed,2024-08-25 05:19:54,NaN,224.0,2
7804,T0007805,C003946,E00969,Bug Report,Low,Closed,2024-04-21 16:45:49,NaN,231.0,2
8433,T0008434,C004257,E00157,Performance,Low,Closed,2020-06-11 04:56:23,NaN,216.0,3
8630,T0008631,C004349,E00433,Security,High,Closed,2025-06-06 09:16:32,NaN,42.0,2
9400,T0009401,C004743,E00194,Performance,Low,Closed,2024-09-07 23:38:21,NaN,164.0,2
9994,T0009995,C005045,E00928,Performance,Low,Closed,2025-04-02 04:15:18,NaN,189.0,2
11735,T0011736,C005912,E00696,Technical,Low,Closed,2023-11-17 22:20:36,NaN,17.0,3
12681,T0012682,C006386,E00029,Feature Request,Low,Closed,2025-09-19 10:38:15,NaN,54.0,5
12853,T0012854,C006473,E01187,Account,High,Closed,2024-03-26 19:23:11,NaN,22.0,4
13137,T0013138,C006613,E01140,Security,Low,Closed,2025-11-22 16:54:12,NaN,234.0,2
13764,T0013765,C006939,E00647,Bug Report,Low,Closed,2025-05-06 18:01:42,NaN,74.0,1
14422,T0014423,C007253,E00082,Billing,Low,Closed,2023-12-08 13:35:52,NaN,113.0,1
15073,T0015074,C007578,E00659,Technical,Medium,Closed,2023-06-03 08:52:47,NaN,99.0,4
15514,T0015515,C007786,E00817,Bug Report,Low,Closed,2025-07-29 14:24:43,NaN,235.0,2
15738,T0015739,C007886,E01283,Technical,Medium,Closed,2020-07-02 00:20:52,NaN,193.0,4
15912,T0015913,C007969,E00750,Performance,Medium,Closed,2019-03-11 14:37:55,NaN,3.0,4
16278,T0016279,C008148,E00804,Billing,Low,Closed,2023-04-26 11:23:42,NaN,62.0,2
16680,T0016681,C008359,E01007,Security,Low,Closed,2018-10-27 03:09:10,NaN,108.0,4
17049,T0017050,C008536,E01002,Feature Request,Critical,Closed,2025-10-03 17:40:15,NaN,183.0,3
17093,T0017094,C008563,E01283,Account,Medium,Closed,2025-08-18 15:46:57,NaN,200.0,4
18123,T0018124,C009051,E00915,Technical,Medium,Closed,2025-01-09 16:13:38,NaN,188.0,4
19279,T0019280,C009649,E00659,Bug Report,Low,Closed,2021-08-08 17:00:33,NaN,44.0,5
19302,T0019303,C009657,E01219,Billing,High,Closed,2025-09-12 00:59:05,NaN,213.0,5
19385,T0019386,C009694,E00521,Bug Report,Low,Closed,2025-09-20 23:01:37,NaN,-5.0,1
19832,T0019833,C009924,E01092,Billing,Medium,Closed,2025-08-11 22:14:40,NaN,223.0,5

I'll let this issue remain for right now and I'll resolve it once I convert Created Date to DateTime dtype, so I ll be able to add the resolution hours to the Created Date to get the Resolved Date and Time

10. usage_logs

In [117]:
usage_logs.isna().sum()

UsageID               0
SubscriptionID        0
CustomerID            0
UsageDate             0
Platform            100
Device                0
Region                0
SessionMinutes        0
APICalls              0
AIRequests            0
StorageGB             0
Logins                0
FilesUploaded         0
ReportsGenerated      0
dtype: int64

In [118]:
usage_logs["Platform"] = usage_logs["Platform"].fillna("Unknown")

In [119]:
usage_logs.isna().sum()

UsageID             0
SubscriptionID      0
CustomerID          0
UsageDate           0
Platform            0
Device              0
Region              0
SessionMinutes      0
APICalls            0
AIRequests          0
StorageGB           0
Logins              0
FilesUploaded       0
ReportsGenerated    0
dtype: int64

Missing values almost dealt with

### Section 4: Duplicates

1. customers

In [120]:
customers.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [121]:
customers.columns

Index(['CustomerID', 'CompanyName', 'Industry', 'Country', 'State', 'City',
       'EmployeeCount', 'AnnualRevenue', 'CompanySize', 'Website', 'JoinDate',
       'SalesRepID', 'CustomerSuccessID', 'CustomerStatus', 'HealthScore'],
      dtype='object')

In [122]:
customers["CustomerID"].duplicated().sum()

np.int64(0)

2. employees

In [123]:
employees.duplicated().sum()

np.int64(0)

In [124]:
employees.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'Department', 'Salary',
       'HireDate', 'PerformanceScore', 'ManagerID'],
      dtype='object')

In [125]:
employees["EmployeeID"].duplicated().sum()

np.int64(0)

3. feature usage

In [126]:
feature_usage.duplicated().sum()

np.int64(0)

In [127]:
feature_usage.columns

Index(['FeatureUsageID', 'SubscriptionID', 'CustomerID', 'Feature',
       'TimesUsed', 'UniqueUsers', 'AvgDurationMinutes', 'LastUsed',
       'PlanName'],
      dtype='object')

In [128]:
feature_usage["FeatureUsageID"].duplicated().sum()

np.int64(0)

4. invoices

In [129]:
invoices.duplicated().sum()

np.int64(0)

In [130]:
invoices.columns

Index(['InvoiceID', 'SubscriptionID', 'CustomerID', 'InvoiceDate', 'DueDate',
       'PlanID', 'PlanName', 'MonthlyPrice', 'DiscountPercent', 'Status',
       'TaxRate', 'Subtotal', 'TaxAmount', 'TotalAmount', 'Currency'],
      dtype='object')

In [131]:
invoices["InvoiceID"].duplicated().sum()

np.int64(0)

5. payments

In [132]:
payments.duplicated().sum()

np.int64(0)

In [133]:
payments.columns

Index(['PaymentID', 'InvoiceID', 'CustomerID', 'PaymentDate', 'PaymentMethod',
       'Amount', 'Currency', 'Status'],
      dtype='object')

In [134]:
payments["PaymentID"].duplicated().sum()

np.int64(0)

In [135]:
payments["InvoiceID"].duplicated().sum()

np.int64(28846)

In [136]:
payments["Amount"].sum()

np.float64(73095412.975)

In [137]:
payments.head(6)

,PaymentID,InvoiceID,CustomerID,PaymentDate,PaymentMethod,Amount,Currency,Status
0,P0000001,I0000002,C006903,2020-07-14 02:15:43,Stripe,148.35,SGD,Completed
1,P0000002,I0000004,C006903,2020-08-29 02:15:43,Debit Card,141.90,SGD,Completed
2,P0000003,I0000007,C006903,2020-11-27 02:15:43,Debit Card,141.90,SGD,Completed
3,P0000004,I0000008,C006903,2021-01-13 02:15:43,Debit Card,135.45,SGD,Completed
4,P0000005,I0000009,C006903,2021-02-07 02:15:43,PayPal,135.45,SGD,Completed
5,P0000006,I0000011,C006903,2021-03-31 02:15:43,Credit Card,139.32,SGD,Completed

In [138]:
payments.groupby("InvoiceID").size().sort_values(ascending=False)

InvoiceID
I0179188    3
I0367450    3
I0471106    3
I0452746    3
I0164718    3
           ..
I0168700    1
I0168698    1
I0168696    1
I0168694    1
I0487488    1
Length: 409538, dtype: int64

In [139]:
payments.loc[

    payments["InvoiceID"] == "I0367450"
]

,PaymentID,InvoiceID,CustomerID,PaymentDate,PaymentMethod,Amount,Currency,Status
330309,P0330310,I0367450,C001815,2021-12-01 20:35:43,Apple Pay,706.17,MYR,Completed
330310,P0330311,I0367450,C001815,2021-12-15 20:35:43,Bank Transfer,372.75,MYR,Completed
438333,P0438334,I0367450,C001815,2021-12-15 20:35:43,Bank Transfer,372.75,MYR,Completed

In [140]:
invoices.columns

Index(['InvoiceID', 'SubscriptionID', 'CustomerID', 'InvoiceDate', 'DueDate',
       'PlanID', 'PlanName', 'MonthlyPrice', 'DiscountPercent', 'Status',
       'TaxRate', 'Subtotal', 'TaxAmount', 'TotalAmount', 'Currency'],
      dtype='object')

In [141]:
invoices.loc[
    invoices["InvoiceID"] == "I0367450"
    ]

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency
367449,I0367450,S011289,C001815,2021-11-22 20:35:43,2021-12-22 20:35:43,6,Enterprise Plus,999,0.0,Paid,8,999.0,79.92,1078.92,MYR

Turns out 2 of the 3 records having same invoice ID but different PaymentID are valid in case of partial payments but the third one is actually just a copy of first one.\
Consequently, any record showing same invoice ID and exact same other attributes like date and time, status ;  is a duplicate and has to be dropped.

In [142]:
payments = payments.drop_duplicates(
    subset=[
        "InvoiceID",
        "PaymentDate",
        "CustomerID",
        "PaymentMethod",
        "Amount",
        "Currency",
        "Status"
    ],
    keep="first"
)

In [143]:
payments["Amount"].sum()

np.float64(73085284.715)

Turns out there was a huge discrepancy in amount paid

6. plans

In [144]:
plans.duplicated().sum()

np.int64(0)

In [145]:
plans.columns

Index(['PlanID', 'PlanName', 'MonthlyPrice', 'BillingCycle', 'APIQuota',
       'StorageLimitGB', 'AIRequests', 'SupportTier'],
      dtype='object')

In [146]:
plans["PlanID"].duplicated().sum()

np.int64(0)

7. refunds

In [147]:
refunds.duplicated().sum()

np.int64(0)

In [148]:
refunds.columns

Index(['RefundID', 'PaymentID', 'InvoiceID', 'CustomerID', 'RefundDate',
       'RefundAmount', 'Reason', 'Status'],
      dtype='object')

In [149]:
refunds["RefundID"].duplicated().sum()

np.int64(0)

In [150]:
refunds["InvoiceID"].duplicated().sum()

np.int64(75)

In [151]:
refunds["PaymentID"].duplicated().sum()

np.int64(25)

In [152]:
refunds.groupby("InvoiceID").size().sort_values(ascending=False)

InvoiceID
I0301786    2
I0066136    2
I0083790    2
I0251187    2
I0301256    2
           ..
I0166011    1
I0166019    1
I0166027    1
I0166080    1
I0487457    1
Length: 17495, dtype: int64

In [153]:
# Sum all refund amounts for each invoice
refund_totals = (
    refunds.groupby("InvoiceID")["RefundAmount"]
    .sum()
    .reset_index(name="TotalRefundAmount")
)

# Merge with invoices
refund_check = invoices.merge(
    refund_totals,
    on="InvoiceID",
    how="inner"
)

# Find invoices where refunds exceed the invoice amount
refund_exceeded = refund_check[
    refund_check["TotalRefundAmount"] > refund_check["TotalAmount"]
]

In [154]:
refund_exceeded

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency,TotalRefundAmount
443,I0013243,S000397,C002516,2025-03-07 22:30:18,2025-04-06 22:30:18,2,Basic,59,0.0,Paid,5,59.00,2.95,61.95,PKR,123.9000
995,I0030515,S000936,C005685,2023-04-10 07:49:05,2023-05-10 07:49:05,2,Basic,59,0.0,Paid,8,59.00,4.72,63.72,AED,127.4400
1287,I0038349,S001170,C005748,2025-06-01 03:35:06,2025-07-01 03:35:06,5,Enterprise,499,0.0,Paid,5,499.00,24.95,523.95,EUR,1047.9000
2111,I0060449,S001842,C006577,2021-03-27 09:19:58,2021-04-26 09:19:58,5,Enterprise,499,120.0,Paid,0,-99.80,-0.00,-99.80,PKR,-67.9500
4769,I0134562,S004177,C002530,2021-12-19 22:59:48,2022-01-18 22:59:48,3,Professional,129,0.0,Paid,18,129.00,23.22,152.22,EUR,304.4400
4835,I0136349,S004234,C005139,2025-07-24 19:06:57,2025-08-23 19:06:57,4,Business,249,15.0,Paid,15,211.65,31.75,243.40,PKR,304.2500
4890,I0138292,S004295,C000311,2025-07-18 18:47:26,2025-08-17 18:47:26,1,Starter,29,0.0,Paid,8,29.00,2.32,31.32,EUR,38.7000
5206,I0147632,S004567,C002745,2025-05-13 02:51:28,2025-06-12 02:51:28,3,Professional,129,15.0,Paid,10,109.65,10.96,120.61,SAR,150.7625
5643,I0160025,S004930,C003969,2021-02-01 10:01:38,2021-03-03 10:01:38,3,Professional,129,0.0,Paid,10,129.00,12.90,141.90,ZAR,283.8000
5930,I0168081,S005178,C009239,2024-02-27 08:34:45,2024-03-28 08:34:45,1,Starter,29,0.0,Paid,0,29.00,0.00,29.00,USD,40.6000
6195,I0175469,S005408,C009813,2021-10-01 08:52:31,2021-10-31 08:52:31,5,Enterprise,499,0.0,Paid,5,499.00,24.95,523.95,AED,1047.9000
6462,I0182732,S005629,C008538,2022-05-14 22:20:58,2022-06-13 22:20:58,1,Starter,29,0.0,Paid,15,29.00,4.35,33.35,AUD,35.5880
6936,I0195329,S006042,C000676,2025-08-03 04:08:55,2025-09-02 04:08:55,3,Professional,129,120.0,Paid,18,-25.80,-4.64,-30.44,PKR,-6.8100
7327,I0205960,S006353,C001046,2024-03-06 17:37:50,2024-04-05 17:37:50,2,Basic,59,0.0,Paid,18,59.00,10.62,69.62,JPY,90.4200
7473,I0209606,S006459,C009798,2018-09-12 15:47:30,2018-10-12 15:47:30,2,Basic,59,0.0,Paid,15,59.00,8.85,67.85,CAD,135.7000
8240,I0230534,S007118,C001059,2023-10-07 10:06:41,2023-11-06 10:06:41,8,Growth,79,10.0,Paid,10,71.10,7.11,78.21,PKR,78.2100
9394,I0262767,S008090,C004323,2020-01-09 01:12:05,2020-02-08 01:12:05,5,Enterprise,499,10.0,Paid,8,449.10,35.93,485.03,INR,748.1800
9870,I0274454,S008460,C007343,2023-05-25 13:26:32,2023-06-24 13:26:32,5,Enterprise,499,0.0,Paid,8,499.00,39.92,538.92,EUR,754.4880
10023,I0278515,S008584,C005600,2025-06-18 16:31:49,2025-07-18 16:31:49,8,Growth,79,0.0,Paid,10,79.00,7.90,86.90,AUD,173.8000
10404,I0288529,S008866,C000574,2025-11-08 12:33:33,2025-12-08 12:33:33,2,Basic,59,0.0,Paid,18,59.00,10.62,69.62,EUR,97.4680
10451,I0289570,S008893,C001058,2025-10-09 07:13:37,2025-11-08 07:13:37,4,Business,249,10.0,Paid,8,224.10,17.93,242.03,EUR,338.8420
10492,I0290733,S008927,C004887,2022-08-05 12:54:46,2022-09-04 12:54:46,3,Professional,129,0.0,Paid,18,129.00,23.22,152.22,AED,213.1080
11659,I0323291,S009924,C000823,2024-01-01 02:47:47,2024-01-31 02:47:47,3,Professional,129,10.0,Paid,5,116.10,5.80,121.90,BRL,243.8000
12053,I0334544,S010294,C000776,2021-06-19 21:21:33,2021-07-19 21:21:33,3,Professional,129,0.0,Paid,15,129.00,19.35,148.35,EUR,207.6900
12308,I0341920,S010522,C005089,2025-07-11 12:13:29,2025-08-10 12:13:29,4,Business,249,0.0,Paid,10,249.00,24.90,273.90,EUR,547.8000
12385,I0344255,S010589,C006930,2022-01-07 03:52:15,2022-02-06 03:52:15,2,Basic,59,0.0,Paid,8,59.00,4.72,63.72,PKR,127.4400
12693,I0352690,S010847,C008399,2024-05-03 03:27:09,2024-06-02 03:27:09,8,Growth,79,10.0,Paid,8,71.10,5.69,76.79,EUR,104.4600
13741,I0382608,S011754,C001809,2025-01-04 05:30:12,2025-02-03 05:30:12,3,Professional,129,0.0,Paid,5,129.00,6.45,135.45,AUD,169.3125
13952,I0388732,S011946,C002847,2021-10-22 20:11:23,2021-11-21 20:11:23,2,Basic,59,120.0,Paid,15,-11.80,-1.77,-13.57,INR,-3.6600
14038,I0391153,S012018,C009881,2022-04-19 20:25:36,2022-05-19 20:25:36,5,Enterprise,499,10.0,Paid,15,449.10,67.36,516.46,SGD,1032.9200
14278,I0398146,S012243,C009381,2021-04-29 01:06:23,2021-05-29 01:06:23,1,Starter,29,10.0,Overdue,15,26.10,3.92,30.02,MYR,60.0400
14643,I0407770,S012539,C003608,2023-10-07 20:22:35,2023-11-06 20:22:35,1,Starter,29,10.0,Paid,15,26.10,3.92,30.02,SAR,60.0400
14669,I0408510,S012570,C002471,2023-12-22 05:45:06,2024-01-21 05:45:06,4,Business,249,15.0,Paid,8,211.65,16.93,228.58,ZAR,457.1600
14815,I0412825,S012718,C003888,2021-04-30 13:48:50,2021-05-30 13:48:50,1,Starter,29,15.0,Paid,15,24.65,3.70,28.35,CAD,40.7200
15527,I0432615,S013324,C005516,2019-12-21 13:30:24,2020-01-20 13:30:24,2,Basic,59,0.0,Paid,15,59.00,8.85,67.85,PKR,135.7000
16023,I0446286,S013740,C005178,2025-06-16 13:24:19,2025-07-16 13:24:19,7,Startup,39,0.0,Paid,10,39.00,3.90,42.90,EUR,43.0000
16127,I0449325,S013824,C004607,2023-01-16 09:48:53,2023-02-15 09:48:53,2,Basic,59,0.0,Paid,8,59.00,4.72,63.72,MYR,89.2080
16776,I0467846,S014387,C000738,2021-12-25 02:28:05,2022-01-24 02:28:05,2,Basic,59,25.0,Paid,5,44.25,2.21,46.46,EUR,65.0440
17401,I0484928,S014918,C001573,2024-04-25 23:05:06,2024-05-25 23:05:06,10,Corporate,349,0.0,Paid,18,349.00,62.82,411.82,GBP,411.8200

In [155]:
invoices.loc[
    invoices["InvoiceID"] == "I0205960"
    ]

,InvoiceID,SubscriptionID,CustomerID,InvoiceDate,DueDate,PlanID,PlanName,MonthlyPrice,DiscountPercent,Status,TaxRate,Subtotal,TaxAmount,TotalAmount,Currency
205959,I0205960,S006353,C001046,2024-03-06 17:37:50,2024-04-05 17:37:50,2,Basic,59,0.0,Paid,18,59.0,10.62,69.62,JPY

In [156]:
refunds.loc[
    refunds["InvoiceID"] == "I0205960"
    ]

,RefundID,PaymentID,InvoiceID,CustomerID,RefundDate,RefundAmount,Reason,Status
1039,R0001040,P0184943,I0205960,C001046,2024-05-18 17:37:50,45.21,Subscription Cancellation,Processed
17528,R0017529,P0184943,I0205960,C001046,2024-05-18 17:37:50,45.21,Subscription Cancellation,Processed

In [157]:
refunds = refunds.drop_duplicates(
    subset=[
        "PaymentID",
        "InvoiceID",
        "CustomerID",
        "RefundDate",
        "RefundAmount",
        "Reason",
        "Status"
    ],
    keep="first"
)

In [158]:
refunds["InvoiceID"].duplicated().sum()

np.int64(51)

On inspecting, Turns out the total amount as in invoice is higher than total refunded amount. Leaving it for Business Rule Validation Section for now.

8. subscriptions

In [159]:
subscriptions.duplicated().sum()

np.int64(0)

In [160]:
subscriptions.columns

Index(['SubscriptionID', 'CustomerID', 'PlanID', 'BillingCycle', 'Status',
       'DiscountPercent', 'StartDate', 'RenewalDate', 'CancelDate',
       'AutoRenew', 'PlanName', 'MonthlyPrice', 'AnnualContractValue'],
      dtype='object')

9. support tickets

In [161]:
support_tickets.duplicated().sum()

np.int64(0)

In [162]:
support_tickets.columns

Index(['TicketID', 'CustomerID', 'AgentID', 'Category', 'Priority', 'Status',
       'CreatedDate', 'ResolvedDate', 'ResolutionHours',
       'CustomerSatisfaction'],
      dtype='object')

10. usage logs

In [163]:
usage_logs.duplicated().sum()

np.int64(0)

In [164]:
usage_logs.columns

Index(['UsageID', 'SubscriptionID', 'CustomerID', 'UsageDate', 'Platform',
       'Device', 'Region', 'SessionMinutes', 'APICalls', 'AIRequests',
       'StorageGB', 'Logins', 'FilesUploaded', 'ReportsGenerated'],
      dtype='object')

### Section 5: DataTypes

1. customers

In [166]:
customers.dtypes

CustomerID            object
CompanyName           object
Industry              object
Country               object
State                 object
City                  object
EmployeeCount          int64
AnnualRevenue        float64
CompanySize           object
Website               object
JoinDate              object
SalesRepID            object
CustomerSuccessID     object
CustomerStatus        object
HealthScore            int64
dtype: object

In [167]:
customers["JoinDate"] = pd.to_datetime(customers["JoinDate"])

In [168]:
customers.dtypes

CustomerID                   object
CompanyName                  object
Industry                     object
Country                      object
State                        object
City                         object
EmployeeCount                 int64
AnnualRevenue               float64
CompanySize                  object
Website                      object
JoinDate             datetime64[ns]
SalesRepID                   object
CustomerSuccessID            object
CustomerStatus               object
HealthScore                   int64
dtype: object

2. employees

In [170]:
employees.dtypes

EmployeeID           object
FirstName            object
LastName             object
Department           object
Salary                int64
HireDate             object
PerformanceScore    float64
ManagerID            object
dtype: object

In [171]:
employees["HireDate"] = pd.to_datetime(employees["HireDate"])

In [172]:
employees.dtypes

EmployeeID                  object
FirstName                   object
LastName                    object
Department                  object
Salary                       int64
HireDate            datetime64[ns]
PerformanceScore           float64
ManagerID                   object
dtype: object

3. feature usage

In [173]:
feature_usage.dtypes

FeatureUsageID         object
SubscriptionID         object
CustomerID             object
Feature                object
TimesUsed               int64
UniqueUsers             int64
AvgDurationMinutes    float64
LastUsed               object
PlanName               object
dtype: object

In [174]:
feature_usage["LastUsed"] = pd.to_datetime(feature_usage["LastUsed"])

In [175]:
feature_usage.dtypes

FeatureUsageID                object
SubscriptionID                object
CustomerID                    object
Feature                       object
TimesUsed                      int64
UniqueUsers                    int64
AvgDurationMinutes           float64
LastUsed              datetime64[ns]
PlanName                      object
dtype: object

4. invoices

In [176]:
invoices.dtypes

InvoiceID           object
SubscriptionID      object
CustomerID          object
InvoiceDate         object
DueDate             object
PlanID               int64
PlanName            object
MonthlyPrice         int64
DiscountPercent    float64
Status              object
TaxRate              int64
Subtotal           float64
TaxAmount          float64
TotalAmount        float64
Currency            object
dtype: object

In [177]:
invoices["InvoiceDate"] = pd.to_datetime(invoices["InvoiceDate"])

In [178]:
invoices["DueDate"] = pd.to_datetime(invoices["DueDate"])

In [179]:
invoices.dtypes

InvoiceID                  object
SubscriptionID             object
CustomerID                 object
InvoiceDate        datetime64[ns]
DueDate            datetime64[ns]
PlanID                      int64
PlanName                   object
MonthlyPrice                int64
DiscountPercent           float64
Status                     object
TaxRate                     int64
Subtotal                  float64
TaxAmount                 float64
TotalAmount               float64
Currency                   object
dtype: object

5. payments

In [180]:
payments.columns

Index(['PaymentID', 'InvoiceID', 'CustomerID', 'PaymentDate', 'PaymentMethod',
       'Amount', 'Currency', 'Status'],
      dtype='object')

In [181]:
payments["PaymentDate"] = pd.to_datetime(payments["PaymentDate"])

C:\Users\talpu\AppData\Local\Temp\ipykernel_11432\673811147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  payments["PaymentDate"] = pd.to_datetime(payments["PaymentDate"])

In [182]:
payments.dtypes

PaymentID                object
InvoiceID                object
CustomerID               object
PaymentDate      datetime64[ns]
PaymentMethod            object
Amount                  float64
Currency                 object
Status                   object
dtype: object

6. plans

In [184]:
plans.dtypes

PlanID             int64
PlanName          object
MonthlyPrice       int64
BillingCycle      object
APIQuota           int64
StorageLimitGB     int64
AIRequests         int64
SupportTier       object
dtype: object

7. refunds

In [185]:
refunds.dtypes

RefundID         object
PaymentID        object
InvoiceID        object
CustomerID       object
RefundDate       object
RefundAmount    float64
Reason           object
Status           object
dtype: object

In [186]:
refunds["RefundDate"] = pd.to_datetime(refunds["RefundDate"])

C:\Users\talpu\AppData\Local\Temp\ipykernel_11432\2734519902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refunds["RefundDate"] = pd.to_datetime(refunds["RefundDate"])

In [187]:
refunds.dtypes

RefundID                object
PaymentID               object
InvoiceID               object
CustomerID              object
RefundDate      datetime64[ns]
RefundAmount           float64
Reason                  object
Status                  object
dtype: object

8. subscriptions

In [188]:
subscriptions.dtypes

SubscriptionID          object
CustomerID              object
PlanID                   int64
BillingCycle            object
Status                  object
DiscountPercent        float64
StartDate               object
RenewalDate             object
CancelDate              object
AutoRenew               object
PlanName                object
MonthlyPrice             int64
AnnualContractValue    float64
dtype: object

In [190]:
date_cols = [
    "StartDate",
    "RenewalDate",
    "CancelDate"
]
for col in date_cols:
    subscriptions[col] = pd.to_datetime(subscriptions[col],errors="coerce")

C:\Users\talpu\AppData\Local\Temp\ipykernel_11432\413622939.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  subscriptions[col] = pd.to_datetime(subscriptions[col],errors="coerce")

In [191]:
subscriptions.dtypes

SubscriptionID                 object
CustomerID                     object
PlanID                          int64
BillingCycle                   object
Status                         object
DiscountPercent               float64
StartDate              datetime64[ns]
RenewalDate            datetime64[ns]
CancelDate             datetime64[ns]
AutoRenew                      object
PlanName                       object
MonthlyPrice                    int64
AnnualContractValue           float64
dtype: object

9. support tickets

In [192]:
support_tickets.dtypes

TicketID                 object
CustomerID               object
AgentID                  object
Category                 object
Priority                 object
Status                   object
CreatedDate              object
ResolvedDate             object
ResolutionHours         float64
CustomerSatisfaction      int64
dtype: object

In [193]:
date_cols = [
    "CreatedDate",
    "ResolvedDate"
]
for col in date_cols:
    support_tickets[col] = pd.to_datetime(support_tickets[col])

In [194]:
support_tickets.dtypes

TicketID                        object
CustomerID                      object
AgentID                         object
Category                        object
Priority                        object
Status                          object
CreatedDate             datetime64[ns]
ResolvedDate            datetime64[ns]
ResolutionHours                float64
CustomerSatisfaction             int64
dtype: object

10. usage logs

In [195]:
usage_logs.dtypes

UsageID              object
SubscriptionID       object
CustomerID           object
UsageDate            object
Platform             object
Device               object
Region               object
SessionMinutes        int64
APICalls              int64
AIRequests            int64
StorageGB           float64
Logins                int64
FilesUploaded         int64
ReportsGenerated      int64
dtype: object

In [196]:
usage_logs["UsageDate"] = pd.to_datetime(usage_logs["UsageDate"])

In [197]:
usage_logs.dtypes

UsageID                     object
SubscriptionID              object
CustomerID                  object
UsageDate           datetime64[ns]
Platform                    object
Device                      object
Region                      object
SessionMinutes               int64
APICalls                     int64
AIRequests                   int64
StorageGB                  float64
Logins                       int64
FilesUploaded                int64
ReportsGenerated             int64
dtype: object